batch_size: 16
iters: 160000

train_dataset: 
  type: Dataset
  dataset_root: data/indoor_lunjiao_seg
  train_path: data/indoor_lunjiao_seg/train.txt
  num_classes: 3
  transforms: #模型训练的数据预处理方式。
  - type: ResizeStepScaling #将原始图像和标注图像随机缩放为0.5~2.0倍
    min_scale_factor: 0.5
    max_scale_factor: 2.0
    scale_step_size: 0.25
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: RandomHorizontalFlip  #对原始图像和标注图像随机进行水平反转
    - type: RandomDistort #对原始图像进行亮度、对比度、饱和度随机变动，标注图像不变
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize #对原始图像进行归一化，标注图像保持不变
  mode: train

val_dataset: 
  type: Dataset
  dataset_root: data/indoor_lunjiao_seg
  val_path: data/indoor_lunjiao_seg/val.txt
  num_classes: 3
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
  mode: val

model:
  type: DDRNet_23
  enable_auxiliary_loss: False
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/cityscapes/ddrnet23_cityscapes_1024x1024_120k/pretrain/model.pdparams

optimizer: #设定优化器的类型
  type: sgd #采用SGD（Stochastic Gradient Descent）随机梯度下降方法为优化器
  momentum: 0.9 #设置SGD的动量
  weight_decay: 4.0e-5 #权值衰减，使用的目的是防止过拟合

loss:
  types:
    - type: OhemCrossEntropyLoss
  coef: [1]

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9
